### ISSUE TITLE
Save Button for Summernote within Form

### ISSUE THREAD

**Issue by ghost** [summernote/awesome-summernote#12]
https://github.com/StudioJunkyard/summernote-save-button

Hope others find this useful.

**Comment by ghost** [comment]
Hi @lqez I realise your very busy, was wondering if you had time to look at this. I"m not sure how to the PR to add this, so did the Issue option.

**Comment by lqez** [comment]
Thanks a lot! I just missed this by mistake. :laughing:

**Comment by lqez** [comment]
Added : https://github.com/summernote/awesome-summernote/commit/6fa23fec8276639dd5e810b8fa26f7f926aa7683

**Comment by ghost** [comment]
All good, I'm just updating the repo, to add an event listener that warns if the page changes without saving the editor contents.
