### ISSUE TITLE
Join Awesome

### ISSUE THREAD

**Issue by lqez** [summernote/awesome-summernote#19]
Add awesome-summernote to https://github.com/sindresorhus/awesome

**Comment by ghost** [comment]
What sort of help are you wanting? I'd be more than happy to vouch for Summernote, and awesome-summernote if you like to get it on that list.

**Comment by lqez** [comment]
Thanks @StudioJunkyard. We should do https://github.com/sindresorhus/awesome/blob/master/create-list.md for joining awesome.

**Comment by lqez** [comment]
Thanks to @outsideris

**Comment by lqez** [comment]
BTW, @outsideris, did we make a pr for this on awesome list? https://github.com/sindresorhus/awesome/blob/master/contributing.md

**Comment by outsideris** [comment]
We didn't. I don't remember whether there was a reason or not.

**Comment by lqez** [comment]
I made a PR : https://github.com/sindresorhus/awesome/pull/849

**Comment by lqez** [comment]
https://github.com/sindresorhus/awesome/pull/849#issuecomment-284701521
Hmm.

**Comment by outsideris** [comment]
Oh no...

**Comment by hackerwins** [comment]
😢
