### ISSUE TITLE
Info about my plugins

### ISSUE THREAD

**Issue by JustinEldracher** [summernote/awesome-summernote#2]
Sorry, I'm still kind of new to Github, and I'm not entirely sure how the Pull Requests and forking work yet, so this will have to do for now.
- [summernote-emoji](https://github.com/JustinEldracher/summernote-plugins/tree/master/summernote-emoji)
  - A dropdown list of my favorite emojiOne images, embedded as base64 strings for easy portability
- [summernote-ext-specialchars](https://github.com/JustinEldracher/summernote-plugins/tree/master/summernote-ext-specialchars)
  - A few tweaks to the official plugin, revising the view and making it more mobile-friendly

**Comment by lqez** [comment]
I've merged your PR! Thanks!
