### ISSUE TITLE
Uploadcare plugin

### ISSUE THREAD

**Issue by dmitry-mukhin** [summernote/awesome-summernote#21]
We've just created a simple plugin for serverless uploading stuff to editor.

Repo: https://github.com/uploadcare/uploadcare-summernote
Demo: https://uploadcare.github.io/uploadcare-summernote/

**Comment by lqez** [comment]
@dmitry-mukhin Thanks. I added it by https://github.com/summernote/awesome-summernote/commit/2750050ab71afd2ed2caf8122ca63c7b5db7c24a
