### ISSUE TITLE
Image manager

### ISSUE THREAD

**Issue by futre** [summernote/awesome-summernote#25]
Hallo, have done a simple image manager for summernote, here a preview http://www.fulviocorsini.it/summernote/ and download from here http://www.fulviocorsini.it/summernote-image-manager click on the last line or just the attached
[summernote-image-manager.zip](https://github.com/summernote/awesome-summernote/files/310838/summernote-image-manager.zip)
 file

I'm sorry but don't how to open a gist or to add the manager to the list.

**Comment by ghost** [comment]
The live demo displays broken images, and they don't insert into the editor, otherwise I like it, well done.

**Comment by futre** [comment]
Sorry, wrong path, it should be work now and the download is disable in the demo,

**Comment by ghost** [comment]
Nice, works well.

**Comment by lqez** [comment]
Thank @futre for using summernote and evolve it. But it would be better if you could offer your repository with just files, not a compressed one.

**Comment by futre** [comment]
Thank, I'm not expert with github, I will correct as soon as possible
