### ISSUE TITLE
vaildate

### ISSUE THREAD

**Issue by leelovejava** [summernote/awesome-summernote#29]
Can support jquery-validate?thanks

**Comment by ghost** [comment]
If anyone's going to go to the effort of implementing a plugin by request, it would help to have a little more context what you expect the plugin to achieve, and even a link to this jQuery script your asking about. (There could be thousands of scripts with the same name, a link to the specific script would be really handy).

**Comment by lqez** [comment]
Sorry, this repository is not for requesting new plugin/extensions.
