### ISSUE TITLE
fontawesome icon picker plugin

### ISSUE THREAD

**Issue by bluecat76** [summernote/awesome-summernote#33]
Hi, I developed a plugin to let a user enter _fontawesome icons_ into summernote. 
There is a working demo here: http://bluecat76.github.io/summernote-faicon/ (use the smiley icon button).

It would be very kind if someone could take a look at it and help me improve functionality. Following improvements would be nice, but I don't know how to do it yet:
- when you search something, the icon gets inserted at the beginning, no matter where the cursor was before in the editor
- ~~Inserting multiple items in a row inserts newer ones to the left, the cursor seems to remain before the inserted item~~ _(updates to insert unicode text instead of fa-... classname)_
- make `self.insertIcon` more flexible, so you can define the markup inserted as icon.
- add an 'onInsert' event

Help is appreciated. I'd also be happy to contribute the plugin by creating a pull request, but I think now it's not stable enough as a plugin.

**Comment by lqez** [comment]
Thank you. But I couldn't see any ‘smiley’ icon on your sample page. Please check it again.
![screen shot 2016-11-08 at 10 12 10 pm](https://cloud.githubusercontent.com/assets/579366/20100355/83e0de10-a600-11e6-9af8-cda8ce815b48.png)

**Comment by bluecat76** [comment]
Hi, thank you for looking into this. 

Now I also had issues getting this to run with plucker, so please note the new URL: http://bluecat76.github.io/summernote-faicon/

The icon should work now. :) And thank you for maintaining Summernote again!

**Comment by lqez** [comment]
Still got the below error. (I was testing with Chrome)
`Refused to execute script from 'https://raw.githubusercontent.com/bluecat76/summernote-faicon/master/faicon/summernote-ext-faicon.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

You can't serve github `raw` file for browsers. Put your script on your github pages and include them as an url of github page like `http://bluecat76.github.io/summernote-faicon/...`, not starts with `https://raw.githubusercontent.com`.

**Comment by bluecat76** [comment]
Sorry for the inconvenience, Firefox only complained about the CSS. 
The files are now available.

**Comment by lqez** [comment]
I tested your module in local and I found a similar problem with your situation.
https://github.com/FortAwesome/Font-Awesome/issues/2799
`span` of `Font-Awesome` does not have any text = zero width element. It makes some disruption on range. (it couldn't be deleted or selected at all)

**Comment by lqez** [comment]
I recommend you to use unicode text as http://fontawesome.io/cheatsheet/

**Comment by bluecat76** [comment]
OK, thank you for the links 👍 , I will look into this.

**Comment by bluecat76** [comment]
The test website is updated (http://bluecat76.github.io/summernote-faicon/index.html). Now, it uses unicode text for the icons.

Improvements:
- Icons can be selected, deleted.
- Inserting multiple icons is done in the right order

**Comment by bluecat76** [comment]
@lqez: do you have an idea, why searching for an icon resets the cursor to the beginning of the edit box? I tried to apply `event.preventDefault` and `event.stopPropagation` in the search box keyup function, so the editor is not influenced, but this changed nothing.

**Comment by lqez** [comment]
I'm back to this issue. Let me give some time to see. Sorry for late.

**Comment by tylerecouture** [comment]
@bluecat76 are you still working on this? I solved the same problem with my emoji plugin, and I'm using a fixed version of yours.  If you want a PR,  can you link to repo?

**Comment by bluecat76** [comment]
Hi @tylerecouture! I haven't worked on this for a while, but I want to update to BS4 soon. A PR would be very much appreciated, the repo is here:
https://github.com/bluecat76/summernote-faicon
Thanks!

**Comment by lqez** [comment]
Please make a PR when it finished
