### ISSUE TITLE
request for add equation plugin.

### ISSUE THREAD

**Issue by nimblemo** [summernote/awesome-summernote#35]
Hi guys! I am developing plugin for insert equations into the text. i have little experience in js, therefore i can't to solve some problems, but this plugin works. If you want to use it, and if you have wish, you may improve it. Thanks.
[summernote-equation-plugin](https://github.com/thisroot/summernote-equation-plugin)

**Comment by lqez** [comment]
Thank you @thisroot. Could you improve your repository with proper welcome page (README.md) with demo pages like other plugins? It should be helpful for summernote users.

**Comment by thisroot** [comment]
Ok, i'll write it during next week.

**Comment by nimblemo** [comment]
[done](https://github.com/thisroot/summernote-equation-plugin/blob/master/README.md)

**Comment by lqez** [comment]
@thisroot Thanks! Then please make a PR for adding `summernote-equation-plugin` into https://github.com/summernote/awesome-summernote#insert section.
