### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by matthewstokeley** [summernote/awesome-summernote#5]
add a background color to the entire panel
https://github.com/matthewstokeley/summernote-background-color

add a full screen background image
https://github.com/matthewstokeley/summernote-background-image

add google fonts - requires datatables
https://github.com/matthewstokeley/summernote-google-fonts

**Comment by lqez** [comment]
@matthewstokeley Nice plugins!
Do you have a plan for writing README.md or a description for them?

**Comment by matthewstokeley** [comment]
Will do soon, thanks

**Comment by lqez** [comment]
I'm closing this. Please reopen or make a new for these.
