### ISSUE TITLE
Big Misc Section

### ISSUE THREAD

**Issue by tylerecouture** [summernote/awesome-summernote#61]
The miscellaneous section is getting pretty big.  Perhaps a new subgroup on Styling/Formatting could be broken out from the Misc group?  Another option would be a Media section, as there are several image and video plugins.

**Comment by lqez** [comment]
Could you make a suggestion with PR?

**Comment by DennisSuitters** [comment]
We may also want to indicate which versions of Summernote a plugin is for.

**Comment by DennisSuitters** [comment]
I added a "Formatting" section, which reduced the "Misc" section significantly.
